apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php.ini: |
    variables_order = "EGPCS"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: opaque
data:
  MYSQL_ROOT_PASSWORD: ZGJwYXNz
  MYSQL_DATABASE: ZGJuYW1l
  MYSQL_USER: ZGJ1c2Vy
  MYSQL_PASSWORD: ZGJwYXNz
  MYSQL_HOST: ZGJfaG9zdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-wp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: httpd-php-container
        image: webdevops/php-apache:alpine-3-php7
        volumeMounts:
        - name: php-config-volume
          mountPath: /opt/docker/etc/php/php.ini
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_HOST                                  

      - name: mysql-container
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_HOST                                  

      volumes: 
      - name: php-config-volume
        configMap:
          name: php-config
---
#lamp service
apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  selector:
    app: lamp-wp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
  type: NodePort
---
#Mysql service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: lamp-wp
  ports:
  - port: 3306
    targetPort: 3306


