apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php.ini: |
    variables_order = "EGPCS"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZGJwYXNz
  MYSQL_DATABASE: ZGJuYW1l
  MYSQL_USER: ZGJ1c2Vy
  MYSQL_PASSWORD: ZGJwYXNz
  MYSQL_HOST: ZGJfaG9zdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-wp
  template:
    metadata:
      labels:
        app: lamp-wp
    spec:
      securityContext:
        fsGroup: 2000  # Specifies the GID for the volume.
      containers:
      - name: httpd-php-container
        image: webdevops/php-apache:alpine-3-php7
        volumeMounts:
        - name: php-config
          mountPath: /app
      - name: mysql-container
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_HOST
      volumes:
      - name: php-config
        configMap:
          name: php-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: lamp-wp
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  selector:
    app: lamp-wp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
  type: NodePort
  
kubectl cp index.php lamp-wp-577946bf99-nj9mc:/app/index.php
kubectl exec -it lamp-wp-577946bf99-nj9mc -- cat app/index.php