## configs & secrets
kubectl create configmap php-config --from-literal=variables_order=EGPCS
kubectl create secret generic mysql-secrets --from-literal=mysql-root-password=root --from-literal=mysql-database=wordpress --from-literal=mysql-user=wpuser --from-literal=mysql-password=wppass --from-literal=mysql-host=mysql-service
## lamp-wp-deploy.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-wp
  template:
    metadata:
      labels:
        app: lamp-wp
    spec:
      containers:
      - name: httpd-php-container
        image: webdevops/php-apache:alpine-3-php7
        ports:
        - containerPort: 80
        volumeMounts:
        - name: php-config
          mountPath: /opt/docker/etc/php/php.ini
          subPath: variables_order
      - name: mysql-container
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-password
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-host
      volumes:
      - name: php-config 
        configMap:
          name: php-config
---
## svcs.yaml
apiVersion: v1 
kind: Service 
metadata:
  name: mysql-service 
spec:
  selector:
    app: lamp-wp 
  ports:
  - protocol: TCP 
    port: 3306 
    targetPort: 3306 
---
apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  type: NodePort 
  selector:
    app: lamp-wp 
  ports:
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 30008
---
kubectl cp index.php lamp-wp-7c64d6f88-kshzl:/app/index.php -c httpd-php-container
kubectl exec lamp-wp-7c64d6f88-kshzl -- printenv
kubectl exec -it lamp-wp-7c64d6f88-kshzl -- /bin/sh

## index.php
<?php
$dbname = 'wordpress';
$dbuser = 'wpuser';
$dbpass = 'wppass';
$dbhost = 'mysql-service';
$connect = mysqli_connect($dbhost, $dbuser, $dbpass) or die("Unable to Connect to '$dbhost'");
$test_query = "SHOW TABLES FROM $dbname";
$result = mysqli_query($test_query);
if ($result->connect_error) {
   die("Connection failed: " . $conn->connect_error);
}
  echo "Connected successfully";