apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-datacenter
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/sysops

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-datacenter
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce


--- 

apiVersion: v1
kind: Pod
metadata:
  name: pod-datacenter
  labels:
    app: pod-datacenter
spec:
  containers:
  - name: container-datacenter
    image: httpd:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - name: pvc-datacenter
        mountPath: /var/www/html
  volumes:
    - name: pvc-datacenter
      persistentVolumeClaim:
        claimName: pvc-datacenter

---

apiVersion: v1
kind: Service
metadata:
  name: web-datacenter
spec:
  type: NodePort
  selector:
    app: pod-datacenter
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008


    