# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-09T20:34:07Z"
  generateName: redis-deployment-54cdf4f76d-
  labels:
    app: redis
    pod-template-hash: 54cdf4f76d
  name: redis-deployment-54cdf4f76d-ns7tl
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: redis-deployment-54cdf4f76d
    uid: a416ef63-009e-46cb-a739-173763bb06a3
  resourceVersion: "1919"
  uid: a0255424-0960-48c1-83e6-0ebd291a5c75
spec:
  containers:
  - image: redis:alpin
    imagePullPolicy: IfNotPresent
    name: redis-container
    ports:
    - containerPort: 6379
      protocol: TCP
    resources:
      requests:
           cpu: 300m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xp796
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kodekloud-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: data
  - configMap:
      defaultMode: 420
      name: redis-config
    name: config
  - name: kube-api-access-xp796
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-10-09T20:34:07Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-10-09T20:34:07Z"
    message: 'containers with unready status: [redis-container]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-10-09T20:34:07Z"
    message: 'containers with unready status: [redis-container]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-10-09T20:34:07Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: redis:alpin
    imageID: ""
    lastState: {}
    name: redis-container
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 172.17.0.2
  phase: Pending
  qosClass: Burstable
  startTime: "2023-10-09T20:34:07Z"