apiVersion: v1
kind: Pod
metadata:
  name: volume-share-devops
  labels:
    name: myapp
spec:
  containers:
  - name: volume-container-devops-1
    image: centos:latest
    command: ["/bin/sleep", "infinity"]
    volumeMounts:
        - name: volume-share
          mountPath: /tmp/news
  - name: volume-container-devops-2
    image: centos:latest
    command: ["/bin/sleep", "infinity"]
    volumeMounts:
        - name: volume-share
          mountPath: /tmp/demo
  volumes:
  - name: volume-share
    emptyDir:
      sizeLimit: 500Mi
