apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: nautilus
data:
  TIME_FREQ: "8"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-volume
  namespace: nautilus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: nautilus
spec:
  containers:
  - name: time-check
    image: busybox:latest
    command:
    - "/bin/sh"
    - "-c"
    - "while true; do date; sleep $TIME_FREQ; done >> /opt/data/time/time-check.log"
    env:
      - name: TIME_FREQ
        valueFrom:
            configMapKeyRef:
              name: time-config          
              key: TIME_FREQ
    volumeMounts:
    - name: log-volume
      mountPath: /opt/data/time
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: log-volume

